spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
    console:
      enabled: true
      path: /console
#      property
init:
  data:
    json:
      path: https://raw.githubusercontent.com/mledoze/countries/master/countries.json
earth:
  radius: 6371000d
#        src/main/resources/json/countries.json